### ISSUE TITLE
`createBar` invalid array length exception due to negative maxBarWidth

### ISSUE THREAD

**Issue by dasilvacontin** [sindresorhus/time-grunt#69]
Reproduced in a < 250px width split. `maxBarWidth` was `-4`.

**Comment by dasilvacontin** [comment]
For now I locally added a `barLength = Math.max(barLength, 0);` to keep the ball rolling.

**Comment by dasilvacontin** [comment]
I'll have to fix this one, it's getting too annoying for me.

**Comment by slinto** [comment]
Hi @dasilvacontin. I can't reproduce this.

**Comment by adrianlee44** [comment]
I was able to reproduce this issue.

<img width="447" alt="screen shot 2016-04-17 at 10 19 33 pm" src="https://cloud.githubusercontent.com/assets/208855/14595080/3a8538de-04f1-11e6-9796-b54e53056cb9.png">

Between https://github.com/sindresorhus/time-grunt/blob/master/index.js#L80-L84, the code is calculating the maxBarWidth by comparing the length of longest task name and column size. I'm assuming the default is half of the column width, otherwise add 20 to the longest task name as padding. The padding ends up creating a negative value.

I have created a PR related to this issue. Let me know what you think
